<?php
namespace App\Service;

use setasign\Fpdi\Fpdi;

class WatermarkService
{
    public function generateWatermark(string $pdfPath): void
    {
        $pdf = new Fpdi();
        $pageCount = $pdf->setSourceFile($pdfPath);

        for ($pageNo = 1; $pageNo <= $pageCount; $pageNo++) {
            $templateId = $pdf->importPage($pageNo);
            $pdf->AddPage();
            $pdf->useTemplate($templateId);

            $pdf->SetFont('Arial', 'B', 30);
            $pdf->SetTextColor(128,128,128);
            // Center the text
            $pdf->SetXY(30, 150);
            $pdf->Write(0, 'Generated by PDF Generator');
        }

        $pdf->Output('F', $pdfPath);
    }
}