version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:latest'
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: wr602d
    ports:
      - '3306:3306'
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - app_network

  app:
    container_name: app-webapp
    image: c7cefb6d6adc4351a61039bd8b12050d40b7fbfc65867c8c4098f863cb181439
    ports:
      - '8080:80'
    volumes:
      - .:/var/www
    networks:
      - app_network
    environment:
      - DATABASE_URL=mysql://root:password@database:3306/wr602d
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

networks:
  app_network:
    external: true