version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:latest'
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: wr602d
    ports:
      - '3306:3306'

  app:
    container_name: app-webapp
    image: db8412534291402e47f6cf5ff1854927462d2550f8f7e99df0f7af3a129e749d  
    ports:
      - '8080:80'
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
