version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:latest'
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: wr602d
    ports:
      - '3306:3306'

  app:
    container_name: app-webapp
    image: 36dec4d66e35b3443398747bc864d66be2632b6601fb3aa2a28314d9360451e4  
    ports:
      - '8080:80'
    volumes:
      - .:/var/www
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
